version: '3.8'

services:
  web:
    image: python:3.9-slim
    working_dir: /app
    volumes:
      - .:/app
    command: bash -c "pip install -r requirements.txt && python app.py"
    ports:
      - "8080:5000"
    environment:
      FLASK_ENV: development